services:
  mysql:
    image: mysql:9.5.0
    container_name: mysql9
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yu51043chie3
      MYSQL_DATABASE: bsdr
      MYSQL_USER: asterisk
      MYSQL_PASSWORD: yu51043chie3
      # TZをAsia/Tokyoに変更（JSTだと認識されないケースがあるため）
      TZ: Asia/Tokyo
    # コマンド引数でMySQL自体のデフォルトタイムゾーンを指定
    command: mysqld --default-time-zone='+09:00'
    volumes:
      - bsdr_mysql_data:/var/lib/mysql

volumes:
  bsdr_mysql_data:
