services:
  mysql:
    image: mysql:9.5.0
    container_name: mysql9
    platform: linux/amd64 # M1/M2 Macの場合
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yu51043chie3
      MYSQL_DATABASE: bsdr
      MYSQL_USER: asterisk
      MYSQL_PASSWORD: yu51043chie3
      TZ: UTC
    volumes:
      - bsdr_mysql_data:/var/lib/mysql

volumes:
  bsdr_mysql_data:
